version: "3.7"
services: 
    mysql:
        container_name: money-manager-database
        image: mysql:8.0.20
        volumes:
            - money-manager-db:/var/lib/mysql
        ports:
            - 3310:3306
        command:
            - --character-set-server=utf8
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: money
            MYSQL_USER: money
            MYSQL_PASSWORD: money

volumes:
    money-manager-db:
        name: money-manager-db