spring:
  application:
    name: Money Manager Backend
    version: 23.1.1
  liquibase:
    change-log: classpath:liquibase/masterChangelog.xml
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    hikari:
      schema: ${DATABASE_SCHEMA}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /money
